config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    root 'users#index'
    resources :users
    resources :sessions, only: [:new, :create, :destroy]
    resources :questions, except: [:show, :new, :index]

    get 'sign_up' => 'users#new'
    get 'log_out' => 'sessions#destroy'
    get 'log_in' => 'sessions#new'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord

  belongs_to :user
  belongs_to :author, class_name: 'User', optional: true

  validates :text, presence: true
  validates :text, length: { maximum: 255 }

end

app/models/user.rb
require 'openssl'

class User < ApplicationRecord

  ITERATIONS = 20000
  DIGEST = OpenSSL::Digest::SHA256.new
  USERNAME_REGEX = /\A\w+\z/
  USERNAME_MAX_LENGTH = 40
  COLOR_REGEX = /\A#[\da-f]{6}\z/

  attr_accessor :password

  has_many :questions, dependent: :destroy

  validates :email, presence: true, uniqueness: true, format: { with: URI::MailTo::EMAIL_REGEXP }
  validates :username, presence: true, uniqueness: true
  validates :username, format: { with: USERNAME_REGEX }, length: { maximum: USERNAME_MAX_LENGTH }
  validates :password, presence: true, on: :create
  validates :password, confirmation: true
  validates :background_color, format: { with: COLOR_REGEX }
  validates :avatar_url, url: { allow_blank: true }

  before_validation :downcase_username_and_email
  before_save :encrypt_password

  def self.authenticate(email, password)
    user = find_by(email: email&.downcase)

    return unless user.present?

    hashed_password = User.hash_to_string(
      OpenSSL::PKCS5.pbkdf2_hmac(
        password, user.password_salt, ITERATIONS, DIGEST.length, DIGEST
      )
    )

    return unless user.password_hash == hashed_password
    user
  end

  def self.hash_to_string(password_hash)
    password_hash.unpack('H*')[0]
  end

  private

  def downcase_username_and_email
    username&.downcase!
    email&.downcase!
  end

  def encrypt_password
    if password.present?
      self.password_salt = User.hash_to_string(OpenSSL::Random.random_bytes(16))

      self.password_hash = User.hash_to_string(
        OpenSSL::PKCS5.pbkdf2_hmac(
          password, password_salt, ITERATIONS, DIGEST.length, DIGEST
        )
      )
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  around_action :switch_locale
  protect_from_forgery with: :exception
  helper_method :current_user

  private

  def switch_locale(&action)
    locale = locale_from_url || locale_from_header || I18n.default_locale
    I18n.with_locale locale, &action
  end

  def locale_from_url
    locale = params[:locale]
    return locale if I18n.available_locales.map(&:to_s).include?(locale)
  end

  def locale_from_header
    I18n.locale = http_accept_language.compatible_language_from(I18n.available_locales)
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def reject_user
    redirect_to root_path, alert: 'У вас недостаточно прав для совершения данного действия!'
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :load_question, only: [:show, :edit, :update, :destroy]
  before_action :authorize_user, except: [:create]

  def edit
  end

  def create
    @question = Question.new(question_params)
    @question.author = current_user

    if @question.save
      redirect_to user_path(@question.user), notice: 'Ваш вопрос задан'
    else
      render :edit
    end
  end

  def update
    if @question.update(question_params)
      redirect_to user_path(@question.user), notice: 'Ваш вопрос сохранен'
    else
      render :edit
    end
  end

  def destroy
    user = @question.user
    @question.destroy
    redirect_to user_path(user), notice: 'Вопрос удален'
  end

  private

  def authorize_user
    reject_user unless @question.user == current_user
  end

  def load_question
    @question = Question.find(params[:id])
  end

  def question_params
    if current_user.present? &&
       params[:question][:user_id].to_i == current_user.id
      params.require(:question).permit(:user_id, :text, :answer)
    else
      params.require(:question).permit(:user_id, :text)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])

    if @user.present?
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Вы успешно залогинились'
    else
      flash.now.alert = 'Неправильный логин или пароль'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Вы разлогинились! Приходите еще!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :load_user, except: [:index, :create, :new]
  before_action :authorize_user, except: [:index, :new, :create, :show]

  def index
    @users = User.all

  end

  def new
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new
  end

  def create
    redirect_to root_path, alert: 'Вы уже залогинены' if current_user.present?
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user), notice: 'Вы успешно зарегистрированы!'
    else
      render 'new'
    end

  end

  def edit

  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: 'Данные обновлены!'
    else
      render 'edit'
    end
  end

  def show
    @questions = @user.questions.order(created_at: :desc)
    @new_question = @user.questions.build

    @questions_count = @questions.count
    @answers_count = @questions.count(&:answer)
    @unanswered_count = @questions_count - @answers_count
  end

  def destroy
    @user.destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Аккаунт успешно удален'
  end

  private

  def authorize_user
    reject_user unless @user == current_user
  end

  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation,
                                 :name, :username, :avatar_url, :background_color)
  end

  def load_user
    @user ||= User.find params[:id]

  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def user_avatar(user)
    if user.avatar_url.present?
      user.avatar_url
    else
      asset_path 'avatar.jpg'
    end
  end

  def fa_icon(icon_class)
    content_tag 'span', '', class: "fa fa-#{icon_class}"
  end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8"/>
  <title><%= t(".title") %></title>
  <link rel="stylesheet"
    href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_pack_tag 'application' %>
</head>

<body>
  <div class="header">
    <div class="container">
      <div class="header-logo">
        <h1 class="header-title"><%= link_to t(".title"), root_path %></h1>
      </div>
      <div class="header-nav">
        <% if current_user %>
        <%= link_to "@#{current_user.username}", user_path(current_user) %> |
        <%= link_to 'Выйти', log_out_path %>
      <% else %>
        <%= link_to 'Зарегистрироваться', sign_up_path,
          class: 'button button-light button-small' %>
        <%= link_to 'Войти', log_in_path,
          class: 'button button-light button-small' %>
      <% end %>
      </div>
    </div>
  </div>

  <div class="content">
    <div class="container">
      <% if flash.any? %>
        <div class="content-wrapper buffer-both">
          <% flash.each do |name, message| %>
            <%= content_tag :div, message, class: "flash-#{name}" %>
          <% end %>
        </div>
      <% end %>
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/questions/_form.html.erb
<div class="form">
  <%= form_for(@question) do |f| %>
    <% if @question.errors.any? %>
      <div class="form-errors">
        <ul>
          <% @question.errors.full_messages.each do |message| %>
            <li class="form-error-message"><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <%= f.hidden_field :user_id %>

  <div class="form-field">
    <%= f.label :text, 'Вопрос', class: 'form-label' %>
    <%= f.text_area :text, class: 'form-textarea' %>
  </div>

  <% if current_user.present? && current_user == @question.user %>
    <div class="form-field">
      <%= f.label :answer, 'Ответ', class: 'form-label' %>
      <%= f.text_area :answer, class: 'form-textarea' %>
    </div>
  <% end %>

    <div class="form-action buffer-both">
      <%= f.submit 'Сохранить', class: 'button button-dark button-small' %>
      или
      <%= link_to "вернуться", user_path(@question.user) %>
    </div>
  <% end %>
</div>

app/views/questions/_question.html.erb
<div class="question">
  <div class="question-content">
    <div class="question-text text-lead">
      <%= question.text %>
    </div>

    <% if question.answer.present? %>
      <div class="question-answer text-lead">
        <%= question.answer %>
      </div>
    <% end %>

    <div class="container">
      <div class="question-date">
        <%= l question.created_at, format: :short %>
      </div>

      <div class="question-date">
        Воспрос от:
        <% if question.author.present? %>
          <%= link_to question.author.username, question.author %>
        <% else %>
          Анонимного пользователя
        <% end %>
      </div>
    </div>
  </div>

  <% if question.user == current_user %>
    <% edit_icon = question.answer.blank? ? 'reply' : 'pencil' %>

    <div class="question-actions">
      <%= link_to fa_icon(edit_icon), edit_question_path(question) %>
      <%= link_to fa_icon('trash-o'), question_path(question),
                  method: :delete, data: {confirm: 'Точно удалить вопрос?'} %>
    </div>
  <% end %>
</div>

app/views/questions/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Вопрос</h1>

  <div class="column-1-2">
    <%# Подключаем паршиал app/views/questions/_form.html.erb %>
    <%= render 'form' %>
  </div>
</div>

app/views/users/edit.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium"><%= t(".title") %></h1>

  <div class="column-1-2">
    <%= form_for(@user) do |f| %>
      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-field">
        <%= f.label :username, class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :avatar_url, class: 'form-label' %>
        <%= f.text_field :avatar_url, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :background_color, class: 'form-label' %>
        <%= f.color_field :background_color, class: 'form-color-field' %>
      </div>

      <div class="buffer-top-large buffer-bottom">
        <%= t(".change_password") %>
      </div>

      <div class="form-field">
        <%= f.label :password, class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="container">

        <div class="form-action buffer-top column-1-2-button">
          <%= f.submit t(".save"), class: 'button button-dark button-small' %>
        </div>

        <div class="form-action buffer-top column-1-2-button">
          <%= link_to 'Удалить аккаунт', @user, data: {method: :delete, confirm: "Вы уверены, что хотите удалить свой аккаунт?"}, class: 'button button-dark button-small' %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<div class="content-wrapper buffer-both text-center">
  <div class="buffer-both">
    <h1 class="title-medium"><%= t("users.index.all_users") %></h1>
  </div>

  <% @users.each do |user| %>
      <div class="users-list-item">
        <div class="user-image-div user-image-div-small">
          <%= link_to image_tag(user_avatar(user), class: 'user-image'), user_path(user) %>
        </div>
      </div>
  <% end %>
</div>

app/views/users/new.html.erb
<div class="container content-wrapper buffer-both">
  <h1 class="title-medium">Присоединяйся к нам!</h1>

  <div class="column-1-2">
    <%= form_for @user do |f| %>

      <% if @user.errors.any? %>
        <div class="form-errors">
          <ul>
            <% for message in @user.errors.full_messages %>
              <li class="form-error-message"><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <div class="form-field">
        <%= f.label :email, 'Логин (email)', class: 'form-label' %>
        <%= f.text_field :email, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :username, 'Никнейм', class: 'form-label' %>
        <%= f.text_field :username, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :name, 'Имя', class: 'form-label' %>
        <%= f.text_field :name, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password, 'Пароль', class: 'form-label' %>
        <%= f.password_field :password, class: 'form-text-field' %>
      </div>

      <div class="form-field">
        <%= f.label :password_confirmation, 'Пароль ещё раз', class: 'form-label' %>
        <%= f.password_field :password_confirmation, class: 'form-text-field' %>
      </div>

      <div class="form-action">
        <%= f.submit 'Зарегистрироваться', class: 'button button-small button-dark' %>
      </div>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="user-header text-center" style="background: <%= @user.background_color %>">
  <h1 class="title-medium"><%= @user.name %></h1>

  <div class="buffer-both">
    <%= link_to 'Редактировать профиль', edit_user_path(@user) if current_user == @user %>
  </div>

  <div class="user-image-div">
    <%= image_tag user_avatar(@user), class: 'user-image', alt: "Фото" %>
  </div>

  <h2 class="title-small buffer-both">@<%= @user.username %></h2>

  <div class="user-ask-button container text-center">
    <%= link_to t('.button_center'), '', class: 'button button-light', id: 'ask-button' %>
  </div>
</div>

<div class="user-question-form-div column-1-4 column-1-4-right" id='ask-form'>
  <div class="user-question-form buffer-both">
    <div class="form">
      <%= form_for @new_question do |f| %>
        <%= f.hidden_field :user_id %>
        <div class="form-field">
          <%= f.label "#{t('.question_label')} @#{@user.username}", class: 'form-label' %>
          <%= f.text_area :text, class: 'form-textarea' %>
        </div>
        <div class="form-action">
          <%= submit_tag t('.button_small'), class: 'button button-small button-dark' %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="column-3-4">
  <div class="user-statistics">
  <div class="questions-count buffer-both-small">
    <div class="column-1-3 text-center">
      <h3 class="title-statistic"><%= t('.all_questions') %>:</h3>
      <p class="text-statistic"><%= @questions_count %> <%= t(".questions_count", count: @questions_count) %></p>
    </div>
    <div class="column-1-3 text-center">
      <h3 class="title-statistic"><%= t('.answered') %>:</h3>
      <p class="text-statistic"><%= @answers_count %> <%= t(".questions_count", count: @answers_count) %></p>
    </div>
    <div class="column-1-3 text-center">
      <h3 class="title-statistic"><%= t('.unanswered') %>:</h3>
      <p class="text-statistic"><%= @unanswered_count %> <%= t(".questions_count", count: @unanswered_count) %></p>
    </div>
  </div>
</div>

  <div class="user-questions buffer-both">
    <div class="questions-list">
      <% @questions.each do |question| %>
        <%= render partial: 'questions/question', object: question %>
      <% end %>
    </div>
  </div>
</div>